### PR TITLE
`leonardo-contrast-colors`: Restore + enhance typescript support

### LINKED ISSUE #143: Typescript support broken
## Description

Class function refactor broke typescript support. Issue identified here: 

https://github.com/adobe/leonardo/issues/113#issuecomment-926028897

## Leonardo package and version

alpha.9+

## Environment
 - **Browser(s) and OS(s):**

### LINKED ISSUE #175: Module '"@adobe/leonardo-contrast-colors"' has no exported member 'BackgroundColor'.
## Description
I'm trying to set up a TypeScript/React project and use `leonardo-contrast-colors` module but I can't import any of the exports.

Apparently this `import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";` points to `index.d.ts` rather than `index.js`.

I wonder if this is a problem with the package or my project configuration. I can't figure it out.

This is my tsconfig.json:

```
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "target": "ES2015",
    "jsx": "react",
    "typeRoots": ["./node_modules/@types"],
    "module": "ESNext",
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"]
}
```

## Steps to reproduce
`npm install @adobe/leonardo-contrast-colors@1.0.0-alpha.13`

Then in the code I do the following according to the example in the README.md:

```
import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";

let gray = new BackgroundColor({
  name: "gray",
  colorKeys: ["#cacaca"],
  ratios: [2, 3, 4.5, 8],
});

let blue = new Color({
  name: "blue",
  colorKeys: ["#5CDBFF", "#0000FF"],
  ratios: [3, 4.5],
});

let red = new Color({
  name: "red",
  colorKeys: ["#FF9A81", "#FF0000"],
  ratios: [3, 4.5],
});

let theme = new Theme({
  colors: [gray, blue, red],
  backgroundColor: gray,
  lightness: 97,
});

```
but I get this error:
Module '"@adobe/leonardo-contrast-colors"' has no exported member 'BackgroundColor'.

## Expected behavior
`import { BackgroundColor, Color, Theme } from "@adobe/leonardo-contrast-colors";` should import BackgroundColor, Color, Theme

## Leonardo package and version
Tried using both 1.0.0-alpha.13 and 1.0.0-alpha.16
According to #173 the latest release is broken.

## Environment
Mac OS

### PR DESCRIPTION
**Pull request by rsek**
Resolves #143, resolves #175 :rocket:

Since I was already rooting around in the declaration file anyways, this PR also integrates content from the README into the TSDoc annotations to expose documentation in IDEs; I've sprinkled in some additional MDN links where relevant.

Something that crossed my mind as I was picking over the code: would there be any interest in a rewrite of `leonardo-contrast-colors` in TS? (Yes, a big ask, but FWIW, I'd be game).

My sense of things is that color spaces and interpolation can be esoteric to even experienced designers and developers. IMO one of the biggest benefits of TS is improving *developer* accessibility via tooling: hints in IDEs, generating API documentation from a "single source of truth", and so on (JSDoc can do a lot of this, but requires a fair bit of human intervention to produce useful TS typings). 

## To-do list
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] Integrate documentation from README as TSDoc annotations
- [x] Include some Typescript string literal templates for CSS colors, in order to clarify acceptable arguments used in various classes and functions. This is many lines of code, but shouldn't have any impact at runtime.
- [x] Test typings in an actual project
    - [x] adjust package.json + file extensions: as `package.json` has `"type": "module"`, the entire package is understood to use ES modules for `*.js` files, making the `*.mjs` extension redundant. using ES modules + `*.mjs`  can cause problems with dependency resolution in some TS environments (e.g. `ts-node`: see https://github.com/TypeStrong/ts-node/issues/1007 ).
- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by NateBaldwinDesign** [comment]
@rsek Thank you so much for taking on those issues in this PR 💯 . I'm not familiar enough with Typescript to appropriately test these changes, but the value proposition mentioned in the description seems very much worthwhile. 

What would the benefits be for rewriting the entire library in Typescript? What would that improve beyond the type definitions that you're already including here?

**Comment by rsek** [comment]
> @rsek Thank you so much for taking on those issues in this PR 100 . I'm not familiar enough with Typescript to appropriately test these changes, but the value proposition mentioned in the description seems very much worthwhile.
> 
> What would the benefits be for rewriting the entire library in Typescript? What would that improve beyond the type definitions that you're already including here?

I think this article gives a good overview of the most common pros and cons with Typescript in general: https://www.altexsoft.com/blog/typescript-pros-and-cons/

One of the things got me thinking on this was this project's `README`, which is great - it's a pretty thorough description of the API. What struck me is that it's about as granular as Typescript gets in many cases: parameter `x` is a string, `y` is an optional boolean, so on.

The way I see it, a lot of Typescript is just explicit documentation that lives next to the code it's describing (and is machine-readable so tooling can take advantage of it and make people's lives easier with e.g. static type checks). From that perspective, Typescript migration would be a migration to a more structured rendering of that same information.

Aside from the benefit to people consuming the library, I think this improves maintainability as well. If the code is living right next to the documentation that describes it, then it's much easier for to maintain parity between the two, and for new contributors to parse out what's going on.

## Other (better?) options

But with all that said -- I mentioned [JSDoc](https://jsdoc.app/) earlier, which literally *is* a standard for inline documentation (that overlaps significantly with TS annotations). Now that I've thought it over more (code migrations are less appealing in the cold light of a February day, ha), I reckon that might be a friendlier path to achieving a similar outcome.

The end result of that would be eliminating a separate `index.d.ts` entirely, and instead include some (fairly verbose) annotations in the JS files themselves, which the TS servers in IDEs can then take advantage of.

The possible downside there is JSDoc vs. IDE handling of imported types, which [can get weird](https://github.com/jsdoc/jsdoc/issues/1645). (Confession: I initially started this PR as JSDoc-based, but ran up against these issues and opted to keep the `*.d.ts` declaration file because I knew I could make that work. In hindsight, I probably should have kept that code around :facepalm:).

## Takeaway

I think my next step here would be to draft a separate PR to explore a JSDoc-based approach further. Even if TS support there leaves something to be desired, it still results in a bunch of comments annotating the original code, which I don't think would be a bad thing, and would be a great starting point for a TS migration if one is later desired.

**Comment by unzico** [comment]
@NateBaldwinDesign Aside from the TypeScript discussion, can the PR please be merged? Right now it's not possible to use this library at all due to the issues fixed in this PR.

A new alpha release with this PR would be very much appreciated! :rocket:

**Comment by NateBaldwinDesign** [comment]
@GarthDB @lazd or @DmitryBaranovskiy able to do this?

**Comment by lazd** [comment]
@NateBaldwinDesign merged! Does this need to be manually released?

**Pull request merged**
