### PR TITLE
[WIP] Add function for creating base scale

### PR DESCRIPTION
**Pull request by NateBaldwinDesign**
## Description

Closes issue #32 

* Added function `generateBaseScale()`
   * Generates color scale using `colorKeys` and `colorspace` parameters
   * Converts all new colors to HSLuv
   * Filters values to remove duplicates for each whole value of HSLuv lightness
   * Returns filtered array in Hex format
* Added tests for `generateBaseScale`
* Updated README with details on how to use the function
* Updated Demo app to use `generateBaseScale` as method of integrating Leonardo for brightness controls.

## Motivation

1. To make brightness controls easier within Leonardo
2. Ensure colors used in brightness controls are uniform in display colorspace (HSLuv) brightness values
3. Ensure output is easily consumable and easy to reason about (0-100 scale)

## To-do list

- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by NateBaldwinDesign** [comment]
After consideration, this may be better suited as a separate package, ie `@adobe/leonardo-base-scale`. 

See issue #34 for possible addition to packages, and how this could come into play.

**Comment by NateBaldwinDesign** [comment]
Work for creating base-scale as separate package moved to separate branch. Given the `contrast-colors` package is stated as housing all functions necessary for creating colors based on contrast ratio, and since `generateBaseScale` is intended for brightness control and use within future `generateContrastTheme` functions, it may be better suited within the same package after all.

**Comment by NateBaldwinDesign** [comment]
@lazd I am curious which direction makes the most sense to you:
1) Add this (and all other contrast-based color generation functions) to the `leonardo-contrast-colors`
Or
2) Create a new package as `leonardo-base-scale`

I feel that the package name `leonardo-contrast-colors` is very specific to the `generateContrastColors` function. As we add functions for generating an entire palette (if part of the same package), the package name seems a bit ambiguous. At which point a more generic name would have been more appropriate.

I am leaning more towards separate packages but want your input.

**Comment by lazd** [comment]
@NateBaldwinDesign hmm, I'm conflicted. If we consider the use cases, will people often be using just either `generateBaseScale` or `generateContrastColors`, or will they often be using both together? 

On one hand, we don't want folks to have to search to find the package they need to provide the right function.

On the other hand, we don't want a single package full of so many methods that it's confusing as to which should be used for a specific use case.

And on the, uh, third hand, perhaps we need to consider unifying these under a single package with a more generic name. It really depends on how people are using these packages.

**Comment by NateBaldwinDesign** [comment]
@lazd true. Once we implement the `generateAdaptiveTheme` function, it may be less likely that the individual `generateContrastColors` function is used, but it would be almost certain that the `generateBaseScale` is less used directly. The base scale function is an aspect of implementing the theme in its entirety but may be useful outside of that, hence the separation. 

This may help to show how the functions are used. 
image

If we separate these all into unique packages, they will all need to import `createScale`, and the `generateAdaptiveTheme` function will need to import both `generateBaseScale` and `generateContrastColors`.

**Comment by NateBaldwinDesign** [comment]
My thoughts on this are
1. If we separate into different packages, we will need a "bundle" for the `generateAdaptiveTheme` that depends on all of them.
2. If we keep them in the same package, `contrast-colors` is not generic enough. 
3. If we generalize the name, we will need to consider I want to add (in the future) helper functions for creating sequential and diverging scales for datavis, which would need the `createScale` helper function but nothing else. Since they're not "contrast-based", they'd likely be separate packages.

One thought, off the top of my head, would be:
* `leonardo-contrast`: Contrast based color and theme generation (all current functions)
* `leonardo-sequential`: Sequential color scale 
* `leonardo-diverging`: Diverging color scale

However, since the sequential/diverging have not yet been implemented, there's also no guarantee that I'll need a package for those. For instance, the web tool may simply provide arguments necessary to output a custom scale using D3's existing API (no wrapper or unique functionality).

**Comment by lazd** [comment]
Like we discussed today, let's reach out to some potential developers that could use Leonardo, give them a demo, and ask them how they imagine Leonardo integrating with their app. Would it be in the build process? CSS-in-JS? CSS custom properties (variables) manipulated at run time? I think this will inform how these functions are separated into different packages and give us a much better idea of how we should recommend the package(s) be used.

**Comment by NateBaldwinDesign** [comment]
Closing this as the `createBaseScale()` function is part of the `generateTheme()` PR. To resolve comments above, we will not be distributing `createBaseScale()` as an individual package. It makes more sense to simply combine all of these into a single resource.

**Pull request closed without merging**
