### PR TITLE
Add Typescript support

### LINKED ISSUE #74: Typescript support
## Description
Hi would be awesome if there is typescript support for this package. I already have done some little work to make it work in my own typescript project: 

## Additional context
I have already done some little work on a start for this to make it work on my own project:
https://gist.github.com/LennardWesterveld/6aca483e6d5db8be79a0655bcae125c0

### PR DESCRIPTION
**Pull request by fedeci**
## Description

This pull request adds index.d.ts file to provide typescript type information about contrast-colors module.
This closes #74

## Motivation

This simplify the use of the module in typescript projects.

## To-do list

- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by NateBaldwinDesign** [comment]
Thank you for this contribution @fedeci !

**Comment by fedeci** [comment]
You're welcome!

**Comment by NateBaldwinDesign** [comment]
FYI this feature added to release 1.0.0-alpha.7

**Comment by KirdesMF** [comment]
is it possible to create an interface for the `colorScales` parameter in the `generateAdaptiveTheme` function ?
 for example :

```ts
const uiRatios = [1, 1.5, 2, 2.5, 3, 4.5, 7, 11, 16];

const redScale: ColorScales = {
   name: 'red',
   ratios: uiRatios,
   colorKeys:  [],
   colorspace: 'HEX'

}

const blueScale: ColorScales = {
   name: 'blue',
   ratios: uiRatios,
   colorKeys:  [],
   colorspace: 'HEX'
}

generateAdaptiveTheme({
   colorScales: [redScale, blueScale],
   baseScale: "red"
})

```
for now I'm just extending the `ContrastColors` module

```ts
declare module ContrastColors {
   type ColorScales = {
      name: string;
      colorKeys: string[];
      colorspace: Colorspace;
      ratios: number[] | { [key: string]: number };
   };
}
```
btw really great work, impressive !!

**Comment by KirdesMF** [comment]
and there is an issue with the `Colorspace` union type:

```ts
  type Colorspace = 'CAM02' | 'CAM02p' | 'LCH' | 'LAB' | 'HSL' | 'HSLuv' | 'RGB' | 'HSV' | 'HEX';
```
[https://github.com/adobe/leonardo/blob/main/packages/contrast-colors/README.md#colorspace-string](url)

HEX provides an issue.

**Comment by KirdesMF** [comment]
Thx ! Next time time should I create an issue ?

**Comment by fedeci** [comment]
If the PR has already been merged it is better to create an issue. 👍

**Pull request merged**
